export const CART_ADD_ITEM_REQUEST = "CART_ADD_ITEM_REQUEST";
export const CART_ADD_ITEM_SUCCESS = "CART_ADD_ITEM_SUCCESS";
export const CART_ADD_ITEM_FAIL = "CART_ADD_ITEM_FAIL";

export const CART_GET_ITEM_REQUEST = "CART_GET_ITEM_REQUEST";
export const CART_GET_ITEM_SUCCESS = "CART_GET_ITEM_SUCCESS";
export const CART_GET_ITEM_FAIL = "CART_GET_ITEM_FAIL";

export const CART_EDIT_ITEM_REQUEST = "CART_EDIT_ITEM_REQUEST";
export const CART_EDIT_ITEM_SUCCESS = "CART_EDIT_ITEM_SUCCESS";
export const CART_EDIT_ITEM_FAIL = "CART_EDIT_ITEM_FAIL";

export const CART_REMOVE_ITEM_REQUEST = "CART_REMOVE_ITEM_REQUEST";
export const CART_REMOVE_ITEM_SUCCESS = "CART_REMOVE_ITEM_SUCCESS";
export const CART_REMOVE_ITEM_FAIL = "CART_REMOVE_ITEM_FAIL";

export const CART_SAVE_SHIPPING_ADDRESS_REQUEST =
  "CART_SAVE_SHIPPING_ADDRESS_REQUEST";
export const CART_SAVE_SHIPPING_ADDRESS_SUCCESS =
  "CART_SAVE_SHIPPING_ADDRESS_SUCCESS";
export const CART_SAVE_SHIPPING_ADDRESS_FAIL =
  "CART_SAVE_SHIPPING_ADDRESS_FAIL";

export const CART_SAVE_PAYMENT_METHOD_REQUEST =
  "CART_SAVE_PAYMENT_METHOD_REQUEST";
export const CART_SAVE_PAYMENT_METHOD_SUCCESS =
  "CART_SAVE_PAYMENT_METHOD_SUCCESS";
export const CART_SAVE_PAYMENT_METHOD_FAIL = "CART_SAVE_PAYMENT_METHOD_FAIL";

export const CART_CLEAR_ITEMS = "CART_CLEAR_ITEMS";
